[package]
name = "problem57"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.15.3"
num-bigint = "0.4.5"
num-traits = "0.2.19"
